package com.ayutaki.chinjufumod;

import net.minecraftforge.fml.common.ModMetadata;

public class ChinjufuModInfoCore {

	public static void registerInfo(ModMetadata meta) {
		meta.modId = ChinjufuMod.MOD_ID;
		meta.name = ChinjufuMod.MOD_NAME;
		meta.description = "This is 'KantaiCollection' Fan Mod. KantaiCollection(DMM GAMES) http://www.dmm.com/netgame/feature/kancolle.html";
		meta.version = ChinjufuMod.MOD_VERSION;
		meta.url = "https://minecraft.curseforge.com/projects/chinjufumod ChinjufuMod_wiki http://chinjufumod.wicurio.com/ ChinjufuMod_Channel https://www.youtube.com/c/ChinjufuModChannel";
		meta.authorList.add("AYUTAKI Shou");
		meta.credits = "Thank you to those who are publishing MOD source code and those who upload maiking MOD videos. I used SE on these sites. 効果音ラボ, On-Jin and niconi commons.";
		meta.logoFile = "chinjufumod.png";
		meta.autogenerated = false;
	}
}
